name: Setup Storm
description: Install Storm CLI and add it to PATH

runs:
  using: composite
  steps:
    - name: Install storm
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/Overal-X/formatio.storm/main/scripts/install.sh | bash
        echo "~/.storm/bin" >> $GITHUB_PATH

    - name: Verify storm
      shell: bash
      run: storm version
